---
- name: Configure local machine
  hosts: all
  roles:
    - role: git
    - role: misc_packages
    - role: gh_extensions
    - role: omz_zshrc
    - role: misc_dotfiles
    - role: vim
    - role: claude
    - role: pi
