---
- hosts: all
  roles:
    - role: git
    - role: misc-packages
    - role: gh-extensions
    - role: omz-zshrc
      when: ansible_facts["os_family"] == "Darwin"
    - role: misc-dotfiles
    - role: claude
