---
- name: Create alacritty config directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/alacritty"
    state: directory
    mode: "0755"

- name: Template alacritty config to $HOME/.config/alacritty/alacritty.toml
  ansible.builtin.template:
    src: templates/alacritty/alacritty.toml.j2
    dest: "{{ ansible_facts['user_dir'] }}/.config/alacritty/alacritty.toml"
    mode: "0644"
