# Reference:
# https://code.claude.com/docs/en/settings.md
# https://code.claude.com/docs/en/permissions.md
claude_settings:
  permissions:
    # Always allow these tools, and never ask for permission to use them. 
    # Add entries in alphabetical order for readability.  Maintain the sections.
    allow:
      - "Bash(cat:*)"
      - "Bash(find:*)"
      # GH cli, mostly read oriented.  
      - "Bash(gh issue list:*)"
      - "Bash(gh issue view:*)"
      - "Bash(gh pr checks:*)"
      - "Bash(gh pr create:*)"
      - "Bash(gh pr diff:*)"
      - "Bash(gh pr list:*)"
      - "Bash(gh pr view:*)"
      - "Bash(gh release list:*)"
      - "Bash(gh release view:*)"
      - "Bash(gh repo view:*)"
      - "Bash(gh run list:*)"
      - "Bash(gh run view:*)"
      # Git commands that are safe to allow without confirmation.  
      - "Bash(git add:*)"
      - "Bash(git commit:*)"
      - "Bash(git diff:*)"
      - "Bash(git log:*)"
      - "Bash(git show:*)"
      - "Bash(git status:*)"
      # Bash-invoked grep.
      - "Bash(grep:*)"
      # Always allow searching
      - "WebSearch"
    defaultMode: "plan"
