---
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade misc MacOS brew packages
  community.general.homebrew:
    name: "{{ macos_brew_packages }}"
    state: latest

- name: Upgrade misc MacOS casks
  community.general.homebrew_cask:
    name: "{{ macos_brew_casks }}"
    state: latest
