---
# tasks file for misc-packages

- name: Install misc packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - diceware
      - rectangle
      - rsync
      - tree
      - yq
      - zip
      - kubectx
  tags:
    - packages
