---
# tasks file for tools-packages

- name: Package installs
  package: 
    name: "{{ packages }}"
    state: present
  become: yes
  vars: 
    packages:
      - jq
      - diceware
      - zsh
      - nano
      - rsync
      - zip
  tags: 
    - packages
  
- name: Conduct Safe Update
  apt:
    upgrade: safe
  become: yes
  tags:
    - never
    - update
  
