---
# tasks file for tools-packages
- name: Install jq
  become: yes
  package:
    name: jq
    state: present
  tags: 
  - packages

- name: Install diceware
  become: yes
  package:
    name: diceware
    state: present
  tags: 
  - packages

- name: Install xclip
  become: yes
  package:
    name: xclip
    state: present
  when: ansible_facts['os_family'] == "Debian"
  tags:
  - packages