---
# tasks file for tools-packages
- name: tools-packages
  block:
  
  - name: Install jq
    package:
      name: jq
      state: present

  - name: Install diceware
    package:
      name: diceware
      state: present

  - name: Install zsh
    package:
      name: zsh
      state: present

  - name: Install nano
    package:
      name: nano
      state: present

  become: yes
  tags: 
  - packages
