---
# tasks file for tools-packages
- name: Install jq
  become: yes
  package:
    name: jq
    state: present
  tags: 
  - packages

- name: Install diceware
  become: yes
  package:
    name: diceware
    state: present
  tags: 
  - packages

- name: Install zsh
  become: yes
  package:
    name: zsh
    state: present
  tags:
  - packages

- name: Install nano
  become: yes
  package:
    name: nano
    state: present
  tags:
  - packages
