---
# tasks file for tools-packages

- name: Package installs
  package: 
    name: "{{ packages }}"
    state: present
  become: yes
  vars: 
    packages:
      - jq
      - diceware
      - zsh
      - nano
      - rsync
  tags: 
    - packages
  
  
