---
# tasks file for tools-packages

- name: Install misc packages
  package: 
    name: "{{ packages }}"
    state: present
  become: yes
  vars: 
    packages:
      - diceware
      - zsh
      - nano
      - rsync
      - zip
  tags: 
    - packages

- name: Install jq
  package:
    name: jq
    state: present
  become: yes
  tags:
    - packages
    - jq

- name: Conduct Safe Update
  apt:
    upgrade: safe
  become: yes
  tags:
    - never
    - update
  
