---
- name: Get list of installed GitHub CLI extensions
  ansible.builtin.command: gh extension list
  register: gh_extensions_list_ext_list_result
  changed_when: false
  when: gh_extensions_authenticated

- name: Install GitHub CLI extensions
  ansible.builtin.command: gh extension install {{ item }}
  loop: "{{ gh_extensions_list }}"
  when:
    - gh_extensions_authenticated
    - item not in (gh_extensions_list_ext_list_result.stdout | default(''))
  changed_when: true
