---
# tasks file for pi

- name: Install pi
  ansible.builtin.include_tasks: pi_install.yml

- name: Configure pi to use claude skills
  ansible.builtin.include_tasks: pi_settings.yml

- name: Install pi-freerouter extension
  ansible.builtin.include_tasks: pi_freerouter_install.yml

- name: Upgrade pi
  ansible.builtin.import_tasks: pi_upgrade.yml
  tags: [upgrade, never]
