---
# tasks file for omz-zshrc

- name: Check that OMZ folder exists
  ansible.builtin.stat:
    path: "{{ homedir.stdout }}/.oh-my-zsh"
  register: omz_zshrc_omz_folder

- name: Check that goenv folder exists
  ansible.builtin.stat:
    path: "{{ homedir.stdout }}/.goenv"
  register: omz_zshrc_goenv_folder

- name: Tfswitch enabled
  # TODO: Refactor this more elegantly later, but this is more of a
  # matter of placement.  Syntactically it is correct.
  ansible.builtin.set_fact:
    omz_zshrc_tfswitch_enabled: true
  when:
    - "'warrensbox/tap/tfswitch' in misc_packages_macos_brew_packages"
    - "misc_packages_brew_packages is defined"
    - "not misc_packages_brew_packages is failed"

- name: Create notice files if they do not exist
  ansible.builtin.copy:
    dest: "{{ homedir.stdout }}/{{ item.file }}"
    content: "{{ item.header }}"
    force: false
    mode: "0644"
  loop: "{{ omz_zshrc_notices }}"
  loop_control:
    label: "{{ item.file }}"

- name: Template zsh configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ homedir.stdout }}/{{ item.dest }}"
    mode: "0644"
  loop:
    # src is relative to templates/ directory in this role
    # dest is relative to the user's home directory
    - src: "zshrc.zsh.j2"
      dest: ".zshrc"
    - src: "zsh-custom/zsh-aliases.zsh.j2"
      dest: ".oh-my-zsh/custom/zsh-aliases.zsh"
    - src: "zsh-custom/zsh-notices.zsh.j2"
      dest: ".oh-my-zsh/custom/zsh-notices.zsh"
  when: "omz_zshrc_omz_folder.stat.exists and omz_zshrc_omz_folder.stat.isdir"

- name: Custom scripts directory
  ansible.builtin.file:
    path: "{{ homedir.stdout }}/.oh-my-zsh/custom/scripts"
    state: directory
    mode: "0755"
  register: omz_zshrc_custom_scripts_dir
  when: "omz_zshrc_omz_folder.stat.exists and omz_zshrc_omz_folder.stat.isdir"

- name: Template goenv
  ansible.builtin.template:
    src: zsh-custom/zsh-goenv.zsh.j2
    dest: "{{ homedir.stdout }}/.oh-my-zsh/custom/zsh-goenv.zsh"
    mode: "0644"
  when: "omz_zshrc_goenv_folder.stat.exists and omz_zshrc_goenv_folder.stat.isdir"

- name: Template git_acp.zsh
  # TODO: remove upon next update
  ansible.builtin.file:
    path: "{{ homedir.stdout }}/.oh-my-zsh/custom/scripts/git_acp.zsh"
    state: absent
