---
# tasks file for git
- name: Set git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ firstname }} {{ lastname }}"
    
- name: Set git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"

- name: Set credential helper
  community.general.git_config:
    name: credential.helper
    scope: global
    value: "{{ git['cred-helper'] }}"

- name: Set ACP alias
  community.general.git_config:
    name: alias.acp
    scope: global
    value: "{{ git['alias-acp'] }}"

