---
- name: Upgrade linux apt packages  # noqa: package-latest
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop: "{{ misc_packages_linux_apt_packages }}"
  become: true
