---
# tasks file for misc-packages

- name: Install macos homebrew packages
  ansible.builtin.include_tasks: brew_packages.yml
  when: ansible_facts["os_family"] == "Darwin"

- name: Install script-based packages
  ansible.builtin.include_tasks: script-packages.yml

- name: Configure GitHub CLI apt repository
  ansible.builtin.include_tasks: gh_apt_repo.yml
  when: ansible_facts["os_family"] == "Debian"

- name: Install linux apt packages
  ansible.builtin.include_tasks: apt_packages.yml
  when: ansible_facts["os_family"] == "Debian"

- name: Check that zsh binary exists
  ansible.builtin.stat:
    path: /usr/bin/zsh
  register: misc_packages_zsh_binary
  when: ansible_facts["os_family"] == "Debian"

- name: Set zsh as default login shell
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  become: true
  when:
    - ansible_facts["os_family"] == "Debian"
    - misc_packages_zsh_binary.stat.exists

- name: Upgrade macOS homebrew packages
  ansible.builtin.import_tasks: brew_upgrade.yml
  when: ansible_facts["os_family"] == "Darwin"
  tags: [upgrade, never]

- name: Upgrade linux apt packages
  ansible.builtin.import_tasks: apt_upgrade.yml
  when: ansible_facts["os_family"] == "Debian"
  tags: [upgrade, never]

- name: Upgrade script-based packages
  ansible.builtin.import_tasks: script-packages-upgrade.yml
  tags: [upgrade, never]
