---
- name: Check if claude is installed
  ansible.builtin.command: which claude
  register: claude_which_claude
  failed_when: false
  changed_when: false

- name: Initialize rtk globally
  ansible.builtin.command: rtk init -g --auto-patch
  args:
    creates: "{{ homedir.stdout }}/.claude/RTK.md"
  when: claude_which_claude.rc == 0
