---
- name: Check if claude is installed
  ansible.builtin.command: which claude
  register: which_claude
  failed_when: false
  changed_when: false

- name: Check if rtk hook is installed
  ansible.builtin.stat:
    path: "{{ homedir.stdout }}/.claude/hooks/.rtk-hook.sha256"
  register: rtk_hook

- name: Initialize rtk globally
  ansible.builtin.command: rtk init -g
  when:
    - which_claude.rc == 0
    - not rtk_hook.stat.exists
