name: Lint

on:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install ansible-core
        run: uv tool install ansible-core

      - name: Install ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: uvx ansible-lint
